import { Link } from "react-router-dom";
import {
  ArrowLeft,
  Shield,
  Lock,
  Database,
  Eye,
  Mail,
  Globe,
  FileText,
  UserCheck,
  AlertTriangle,
  Fingerprint,
  Camera,
  Cloud,
  Megaphone,
  Smartphone,
  Trash2,
  KeyRound,
} from "lucide-react";
import { Button } from "@/components/ui/button";

const LAST_UPDATED = "July 25, 2026";

const Section = ({
  icon: Icon,
  title,
  children,
}: {
  icon: any;
  title: string;
  children: React.ReactNode;
}) => (
  <section className="wood-panel border border-border rounded-lg p-5 md:p-6">
    <div className="flex items-center gap-3 mb-3">
      <div className="brass-gradient rounded-md p-2">
        <Icon className="h-4 w-4 text-primary-foreground" />
      </div>
      <h2 className="font-display text-xl font-bold brass-text">{title}</h2>
    </div>
    <div className="text-sm text-foreground/85 leading-relaxed space-y-2">
      {children}
    </div>
  </section>
);

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background">
      <header className="wood-panel border-b border-border sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link to="/">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-4 w-4 mr-1" /> Back
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            <Shield className="h-4 w-4 text-primary" />
            <span className="font-display font-semibold brass-text text-sm">
              DocLocker Privacy
            </span>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 space-y-5">
        <div className="text-center mb-2">
          <h1 className="font-display text-3xl md:text-4xl font-bold brass-text mb-2">
            Privacy Policy
          </h1>
          <p className="text-xs text-muted-foreground">
            Last updated: {LAST_UPDATED}
          </p>
          <p className="mt-4 text-sm text-muted-foreground max-w-xl mx-auto">
            This page is maintained by the DocLocker app owner to explain what
            data DocLocker collects, how it is used, where it is stored, and
            the choices you have. Your privacy and the safety of your
            documents are our top priority.
          </p>
        </div>

        <Section icon={FileText} title="1. Who We Are">
          <p>
            DocLocker is a personal document vault that lets you scan, snap,
            store, organize, view, edit, and protect your important files
            (IDs, certificates, receipts, photos, PDFs, spreadsheets, Word
            documents and more) behind multi-factor security.
          </p>
          <p>
            This policy describes what information the app collects, how it is
            used, where it is stored, and the choices you have. By creating
            an account or using DocLocker you agree to this policy.
          </p>
        </Section>

        <Section icon={Database} title="2. Information We Collect">
          <p>
            <strong>Account information.</strong> Email address, optional
            phone number and country code, hashed password and (where
            applicable) hashed 5-digit PIN, and the authentication method you
            choose (email &amp; password, Google Sign-In, or phone + PIN).
          </p>
          <p>
            <strong>Security setup.</strong> The factors you register during
            security setup — a chosen face/ID image, a passkey / device
            biometric (WebAuthn) credential handle, a school name, a family
            member's name of your choice, recovery questions, and one-time
            email codes. Sensitive answers are stored as one-way hashes or
            protected references, not as plain text where it would weaken
            security.
          </p>
          <p>
            <strong>Your documents.</strong> The files you upload, scan, or
            save to your drawers, together with their name, size, file type,
            the drawer they live in, and timestamps. This includes
            multi-page PDFs generated by the scanner and images captured with
            the camera.
          </p>
          <p>
            <strong>Subscription &amp; usage.</strong> Your current plan,
            storage usage, drawer counts, and basic activity needed to
            enforce free / premium limits and auto-lock the vault.
          </p>
          <p>
            <strong>Device &amp; technical data.</strong> Browser / WebView
            type, language preference, connection state (online/offline),
            and limited diagnostics needed to keep the app working (for
            example, to recover from a failed upload or a slow phone).
          </p>
          <p>
            We do <strong>not</strong> sell your data, and we do{" "}
            <strong>not</strong> mine the contents of your documents to build
            advertising profiles about you.
          </p>
        </Section>

        <Section icon={Camera} title="3. Camera, Scanner &amp; AI Cleanup">
          <p>
            The app uses your device camera only while you are on the scan or
            take-photo screen. Frames are processed on the device to detect
            document edges, warp perspective, and apply brightness / contrast
            cleanup.
          </p>
          <p>
            <strong>AI document cleanup.</strong> When you use the scanner,
            the captured image may be sent over HTTPS to an AI service to
            enhance edges, remove glare, and clean shadows while keeping
            words readable. The cleaned image is returned to your device and
            saved to your vault (or offered as a download). The AI provider
            is instructed not to use your images to train public models.
          </p>
          <p>
            <strong>Two-Sided ID mode</strong> captures the front and back of
            an ID as a single combined image. Both sides are treated with the
            same protections as any other document.
          </p>
          <p>
            <strong>Multi-page scanning.</strong> You can add additional
            pages to a scan; all pages are combined into a single PDF on your
            device before being saved.
          </p>
        </Section>

        <Section icon={Eye} title="4. How We Use Your Information">
          <ul className="list-disc pl-5 space-y-1">
            <li>To create and secure your account and verify your identity.</li>
            <li>To store, display, edit, rename, search, and let you download your documents.</li>
            <li>To run multi-factor verification, auto-lock, and account recovery.</li>
            <li>To enforce free / premium storage limits and process upgrades.</li>
            <li>To detect abuse, prevent unauthorized access, and improve reliability.</li>
            <li>To send essential service messages (security alerts, recovery codes, receipts).</li>
            <li>To keep the app usable offline and sync changes when you are back online.</li>
          </ul>
        </Section>

        <Section icon={Lock} title="5. How Your Documents Are Protected">
          <ul className="list-disc pl-5 space-y-1">
            <li>Files are uploaded over HTTPS to private cloud storage that is not publicly listable.</li>
            <li>Access to your files is gated by per-user database rules (row-level security) so only your authenticated account can read them.</li>
            <li>The vault is locked behind multi-factor security: you register at least 3 of 6 factors and must pass at least 2 to unlock.</li>
            <li>The app auto-locks after a short period of inactivity (configurable, up to a maximum of 2 minutes). Auto-lock pauses while you are actively scanning or saving.</li>
            <li>Deleting a document requires a reason and security re-verification to prevent accidental or hostile deletion.</li>
            <li>Passwords and PINs are stored as one-way hashes; the app cannot show them back to you.</li>
          </ul>
          <p className="text-xs text-muted-foreground pt-2">
            No internet service can guarantee perfect security. You are
            responsible for keeping your password, PIN, recovery codes, and
            device safe.
          </p>
        </Section>

        <Section icon={Fingerprint} title="6. Biometrics (Fingerprint / Face)">
          <p>
            DocLocker supports device biometrics (fingerprint or face
            unlock) as one of the security factors, using the WebAuthn
            standard and/or the native biometric bridge exposed by supported
            Android shells.
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Your fingerprint or face image <strong>never leaves your device</strong>. The app only receives a yes/no result from the phone's secure hardware.</li>
            <li>The app stores only an opaque credential handle so it can ask the phone to verify you next time.</li>
            <li>You can remove the biometric factor at any time by re-running security setup.</li>
          </ul>
        </Section>

        <Section icon={KeyRound} title="7. Account Recovery">
          <p>
            If you forget your password or PIN you can recover access using
            any of the factors you registered — a recovery question, a
            one-time code sent to your email, your registered school name,
            your chosen family member's name, or by contacting support with
            proof of ownership.
          </p>
          <p>
            One-time codes are short-lived and single-use. Recovery attempts
            are rate-limited to protect against brute-force attacks.
          </p>
        </Section>

        <Section icon={Smartphone} title="8. Offline Use &amp; Local Storage">
          <p>
            DocLocker is a progressive web app (PWA). To keep working when
            you lose connectivity, the app caches its own code and a small
            queue of pending actions on the device.
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Files you scan or edit while offline are held in a local queue and uploaded automatically the next time you are online.</li>
            <li>The app can be registered as a system-wide document opener via Web File Handlers; when you tap a supported file elsewhere on your phone, DocLocker can offer to open it.</li>
            <li>Saving a file to your phone uses your device's normal download or share pathway. DocLocker does not read other files from your device without your explicit picker action.</li>
          </ul>
        </Section>

        <Section icon={Cloud} title="9. Third-Party Services">
          <p>DocLocker relies on a small number of trusted providers to operate:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Cloud backend &amp; storage</strong> — hosts your account, database rows, and document files, and runs the secure functions used for phone + PIN sign-in, PIN reset, and download mirroring.</li>
            <li><strong>Google Sign-In</strong> (optional) — only if you choose to sign in with Google. Google shares your basic profile (name, email, avatar) with the app.</li>
            <li><strong>AI document cleanup</strong> — see §3.</li>
            <li><strong>Payment processing</strong> — handled through a manual verification flow you control; we never store full card numbers.</li>
            <li><strong>Advertising</strong> — see §10.</li>
          </ul>
        </Section>

        <Section icon={Megaphone} title="10. Advertising">
          <p>
            The free tier of DocLocker is supported by advertising. The paid
            tier removes ads.
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Banner ads</strong> may appear on the landing screen and on the verification screen. They refresh at most once per minute.</li>
            <li><strong>Interstitial (full-screen) ads</strong> may appear only after specific, user-initiated actions such as completing 2-step verification or saving a file to your phone from the public screen. A 2-minute cooldown is enforced between interstitials.</li>
            <li>Ads never appear on route changes, on the back button, or on sign-out.</li>
            <li>The advertising SDK may read a device-generated advertising identifier and coarse device information (WebView type, language, connection state) to select relevant ads. It does not receive the contents of your documents.</li>
            <li>You can reset or opt out of the advertising identifier in your device settings, or upgrade to the paid tier to remove ads entirely.</li>
          </ul>
        </Section>

        <Section icon={UserCheck} title="11. Your Rights &amp; Choices">
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Access &amp; download.</strong> You can view and download any document from your drawers at any time.</li>
            <li><strong>Edit &amp; rename.</strong> You can rename, edit (where supported: text, .docx, .xlsx), or delete documents and drawers.</li>
            <li><strong>Search.</strong> Vault drawers support real-time filename search so you can find files quickly.</li>
            <li><strong>Batch upload.</strong> You can select and store multiple files at once.</li>
            <li><strong>Delete your account.</strong> You may request full account and data deletion by contacting us at the address below.</li>
            <li><strong>Language.</strong> The app is available in 12 languages and can always be restored to English from the language selector.</li>
            <li><strong>Withdraw consent.</strong> You can stop using the app at any time; uninstalling and deleting your account removes your stored data.</li>
          </ul>
        </Section>

        <Section icon={Trash2} title="12. Data Retention">
          <p>
            Your documents and account data are retained for as long as your
            account is active. If your subscription expires, your drawers
            are frozen (not deleted) so you can renew without losing data.
            If you ask us to delete your account, your files and personal
            data are permanently removed from active storage within 30 days,
            except where we are required by law to keep limited records.
          </p>
          <p>
            Locally cached data (offline queue, PWA cache) is removed when
            you sign out, clear browser data, or uninstall the app.
          </p>
        </Section>

        <Section icon={Shield} title="13. Children's Privacy">
          <p>
            DocLocker is intended for users aged 13 and over (or the minimum
            age of digital consent in your country). We do not knowingly
            collect personal data from younger children. If you believe a
            child has created an account, please contact us so we can remove
            it.
          </p>
        </Section>

        <Section icon={Globe} title="14. International Use">
          <p>
            DocLocker is available worldwide and is translated into 12
            languages. By using the app you understand that your data may be
            processed in countries other than your own, including in regions
            where data-protection laws may differ. We apply the same
            security and access controls regardless of where you sign in
            from.
          </p>
        </Section>

        <Section icon={AlertTriangle} title="15. Permissions Used">
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Camera</strong> — required to scan or photograph documents. Used only while you are on the capture screen.</li>
            <li><strong>Storage / Files</strong> — required to open files from your device and to save downloaded files.</li>
            <li><strong>Biometrics</strong> — optional. Used only if you choose fingerprint / face as a security factor.</li>
            <li><strong>Network</strong> — required to sync your vault, run AI cleanup, and load ads on the free tier.</li>
            <li><strong>Notifications</strong> — optional; used only for essential service alerts.</li>
          </ul>
        </Section>

        <Section icon={FileText} title="16. Changes to This Policy">
          <p>
            We may update this policy as the app evolves. When we make
            material changes we will update the "Last updated" date at the
            top of the page and, where appropriate, notify you inside the
            app. Continued use of DocLocker after a change means you accept
            the updated policy.
          </p>
        </Section>

        <Section icon={Mail} title="17. Contact Us">
          <p>
            Questions, complaints, or data-deletion requests? Reach the
            DocLocker team at:
          </p>
          <p className="font-medium">
            <a
              href="mailto:ndamson8@gmail.com"
              className="text-primary underline"
            >
              ndamson8@gmail.com
            </a>
          </p>
          <p className="text-xs text-muted-foreground">
            Web:{" "}
            <a
              href="https://scanstore.ndamwesigaapp.store/privacy"
              className="text-primary underline"
            >
              scanstore.ndamwesigaapp.store/privacy
            </a>
          </p>
        </Section>

        <footer className="text-center text-xs text-muted-foreground pt-4 pb-8">
          © {new Date().getFullYear()} DocLocker. All rights reserved.
        </footer>
      </main>
    </div>
  );
}
